name: CI Backend - Python

on:
  push:
    branches:
      - main     # Run CI on push to main branch
      - dev      # Run CI on push to dev branch
  pull_request:  # Run CI on pull requests

jobs:
  build:
    runs-on: ubuntu-latest   # Use Ubuntu virtual machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4   # Get code from repository

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build check
        run: |
          python -m compileall app
